const AXIS_META = {
  organ: { label: 'Organ Wise', icon: 'Heartbeat', color: '#0F5DA8' },
  disease: { label: 'Disease Wise', icon: 'Warning', color: '#c62828' },
  disorder: { label: 'Disorder Wise', icon: 'Shield', color: '#7b1fa2' },
  age: { label: 'Age Wise', icon: 'User', color: '#2e7d32' },
  gender: { label: 'Gender Wise', icon: 'Heart', color: '#e65100' },
  lifestyle: { label: 'Lifestyle Wise', icon: 'Lightbulb', color: '#FF8A00' },
  lifeStage: { label: 'Life Stage Wise', icon: 'Baby', color: '#ec407a' },
  symptom: { label: 'Symptom Wise', icon: 'Warning', color: '#ff7043' },
  occupation: { label: 'Occupation Wise', icon: 'Suitcase', color: '#5c6bc0' },
  medication: { label: 'Medication Monitoring', icon: 'Pill', color: '#26a69a' },
  familyHistory: { label: 'Family History / Genetic', icon: 'Heartbeat', color: '#ef5350' },
  seasonal: { label: 'Seasonal Wise', icon: 'Cloud', color: '#42a5f5' },
  diet: { label: 'Diet Wise', icon: 'ForkKnife', color: '#66bb6a' },
  postRecovery: { label: 'Post-Recovery Wise', icon: 'Heartbeat', color: '#ab47bc' },
  travel: { label: 'Travel Wise', icon: 'Airplane', color: '#ffa726' },
  insurance: { label: 'Insurance / Corporate', icon: 'Briefcase', color: '#78909c' },
  preventive: { label: 'Preventive Screening', icon: 'Shield', color: '#26c6da' },
  budget: { label: 'Budget / Price Tier', icon: 'Coin', color: '#ffca28' },
  risk: { label: 'Risk Profile', icon: 'Warning', color: '#ef5350' },
  duration: { label: 'Duration / Urgency', icon: 'Clock', color: '#8d6e63' },
  mentalHealth: { label: 'Mental Health', icon: 'Heart', color: '#7e57c2' },
  fitness: { label: 'Fitness & Sports', icon: 'Lightning', color: '#ff7043' },
  sleep: { label: 'Sleep Health', icon: 'Moon', color: '#5c6bc0' },
  environmental: { label: 'Environmental / Toxin', icon: 'Leaf', color: '#66bb6a' },
  vaccination: { label: 'Vaccination & Immunity', icon: 'Syringe', color: '#42a5f5' },
  preSurgical: { label: 'Pre-Surgical', icon: 'FirstAid', color: '#ef5350' },
  ethnicity: { label: 'Ethnicity / Region', icon: 'Globe', color: '#ab47bc' },
  fertility: { label: 'Fertility & Reproductive', icon: 'Heart', color: '#ec407a' },
};

const PACKAGE_DEFS = [
  // ── 1. ORGAN WISE ──
  { slug: 'liver-health', name: 'Liver Health Package', axis: 'organ',
    desc: 'Comprehensive liver function assessment including enzymes, bilirubin, proteins, and hepatitis screening.',
    match: c => /liver|bilirubin|SGPT|ALT|SGOT|AST|GGT|alkaline phosphatase|hepatitis/i.test(c) },
  { slug: 'cardiac-care', name: 'Cardiac Risk Assessment', axis: 'organ',
    desc: 'Complete heart health evaluation with lipid profile, cardiac enzymes, and inflammatory markers.',
    match: c => /cardiac|lipid|cholesterol|triglyceride|hs.crp|troponin|nt.probnp|bnp|homocysteine|apolipoprotein|ck-mb|heart/i.test(c) },
  { slug: 'kidney-health', name: 'Kidney Function Package', axis: 'organ',
    desc: 'Kidney health screening covering filtration markers, electrolytes, and early damage detection.',
    match: c => /kidney|renal|creatinine|bun|urea|uric acid|microalbumin|cystatin|nephropathy|glomerular|osmolality|anion gap/i.test(c) },
  { slug: 'thyroid-care', name: 'Thyroid Wellness Package', axis: 'organ',
    desc: 'Full thyroid evaluation including TSH, T3, T4, and thyroid antibodies for complete thyroid health.',
    match: c => /thyroid|tsh|t3|t4|tpo|anti.thyroglobulin|thyroid antibody/i.test(c) },
  { slug: 'pancreas-health', name: 'Pancreatic Function Package', axis: 'organ',
    desc: 'Pancreatic health assessment including enzymes, insulin, and glucose metabolism markers.',
    match: c => /pancreatic|amylase|lipase|insulin|c-peptide|glucagon|elastase/i.test(c) },
  { slug: 'bone-health', name: 'Bone & Joint Health Package', axis: 'organ',
    desc: 'Bone health screening with calcium metabolism, vitamin D, and bone turnover markers.',
    match: c => /calcium|bone|vitamin D|osteoporosis|osteocalcin|PTH|parathyroid|phosphorus|magnesium|vitamin K/i.test(c) },
  { slug: 'lungs-respiratory', name: 'Lungs & Respiratory Health Package', axis: 'organ',
    desc: 'Respiratory health assessment including lung function markers, infection screening, and TB detection.',
    match: c => /respiratory|tb|tuberculosis|quantiFERON|geneXpert|COVID|covid|sputum|lung|pulmonary|sweat chloride|RSV|influenza|adenovirus|pneumonia/i.test(c) },
  { slug: 'brain-neurological', name: 'Brain & Neurological Health Package', axis: 'organ',
    desc: 'Neurological health screening covering essential markers for brain function, inflammation, and neurotransmitter balance.',
    match: c => /neurotransmitter|pregnenolone|copper|ceruloplasmin|homocysteine|vitamin B12|folate|magnesium|ana|anti.*cardiolipin/i.test(c) },
  { slug: 'skin-health', name: 'Skin & Allergy Health Package', axis: 'organ',
    desc: 'Skin health assessment covering allergy markers, autoimmune skin conditions, and mast cell disorders.',
    match: c => /allergy|mast cell|tryptase|histamine|ige|eosinophil|cationic protein|contact|cryoglobulin|complement/i.test(c) },
  { slug: 'eye-health', name: 'Eye Health Checkup', axis: 'organ',
    desc: 'Vision and eye health screening covering inflammation markers, vascular health, and nutritional status.',
    match: c => /vitamin A|retinol|hs.crp|homocysteine|inflammatory|autoimmune|diabetes|hba1c/i.test(c) },

  // ── 2. DISEASE WISE ──
  { slug: 'diabetes-care', name: 'Diabetes Care Package', axis: 'disease',
    desc: 'Complete diabetes screening and monitoring with blood sugar, HbA1c, insulin, and ketone markers.',
    match: c => /diabetes|HbA1c|glucose|insulin|ketone|fructosamine|hypoglycemia|gestational|OGTT|postprandial/i.test(c) },
  { slug: 'hypertension-package', name: 'Hypertension & Cardiac Risk Package', axis: 'disease',
    desc: 'Blood pressure and heart health screening covering cardiac markers, electrolytes, and kidney function.',
    match: c => /cardiac|lipid|hs.crp|homocysteine|apolipoprotein|lipoprotein|creatinine|bun|electrolyte|sodium|potassium|aldosterone|renin|cortisol/i.test(c) },
  { slug: 'cancer-screening', name: 'Cancer Screening Package', axis: 'disease',
    desc: 'Multi-cancer early detection with tumor markers for common cancers.',
    match: c => /cancer|tumor|ca 125|ca 19-9|ca 15-3|psa|cea|afp|cyfra|scc|nse|pap smear|brca|occult blood|thyroglobulin|calcitonin|he4|galad/i.test(c) },
  { slug: 'hepatitis-package', name: 'Hepatitis Screening Package', axis: 'disease',
    desc: 'Complete hepatitis screening covering Hepatitis B and C, liver function, and autoimmune hepatitis markers.',
    match: c => /hepatitis|liver.*function|bilirubin|sgpt|alt|sgot|ast|ggt|hbsag|anti.*hcv|autoimmune.*hepatitis|anti.*lkm|anti.*sma|anti.*mitochondrial|ama|igg.*liver/i.test(c) },
  { slug: 'pcos-package', name: 'PCOS & Hormonal Health Package', axis: 'disease',
    desc: 'Comprehensive PCOS evaluation covering hormones, glucose metabolism, lipid profile, and thyroid function.',
    match: c => /hormone|cortisol|prolactin|testosterone|estradiol|progesterone|fsh|lh|amh|dhea|shbg|androstenedione|17-oh|insulin|hba1c|glucose|lipid|thyroid|shbg|leptin|adiponectin/i.test(c) },
  { slug: 'hiv-std-package', name: 'HIV & STD Screening Package', axis: 'disease',
    desc: 'Comprehensive sexually transmitted infection screening including HIV, Hepatitis B/C, and syphilis.',
    match: c => /HIV|Hepatitis B|Hepatitis C|VDRL|RPR|syphilis|STD|herpes|HSV|HPV|chlamydia|gonorrhea/i.test(c) },
  { slug: 'anemia-package', name: 'Anemia & Iron Deficiency Package', axis: 'disease',
    desc: 'Complete anemia workup with iron studies, B12, folate, and hemolysis markers.',
    match: c => /anemia|iron|ferritin|tibc|transferrin|haptoglobin|hemoglobin.*electro|thalassemia|sickle|red cell.*enzyme|g6pd|pyruvate.*kinase|reticulocyte|rdw|ch?r|mcv|mch|mchc/i.test(c) },
  { slug: 'tb-package', name: 'TB (Tuberculosis) Screening Package', axis: 'disease',
    desc: 'Complete tuberculosis detection including IGRA, chest-related markers, and TB-specific PCR.',
    match: c => /tb|tuberculosis|quantiFERON|geneXpert|ada|sputum|mantoux|culture.*tb|acid fast/i.test(c) },
  { slug: 'arthritis-care', name: 'Arthritis & Autoimmune Package', axis: 'disease',
    desc: 'Comprehensive arthritis and autoimmune disease screening with specific antibody markers.',
    match: c => /arthritis|rheumatoid|uric acid|gout|autoimmune|anti-ccp|ana|anti.dsdna|hla-b27|anca|complement|anti.*smith|anti.*RNP|sjogren|scleroderma|myositis|vasculitis|anti.*cardiolipin|copper|ceruloplasmin|cryoglobulin|immune complex/i.test(c) },
  { slug: 'liver-disease', name: 'Liver Disease Screening Package', axis: 'disease',
    desc: 'Comprehensive screening for liver diseases including viral hepatitis, fatty liver, and cirrhosis markers.',
    match: c => /liver|hepatitis|bilirubin|sgpt|alt|sgot|ast|ggt|alkaline.*phosphatase|albumin|total.*protein|ammonia|fibrosis|cirrhosis|fatty.*liver|nafld/i.test(c) },

  // ── 3. DISORDER WISE ──
  { slug: 'autoimmune-package', name: 'Autoimmune Disorder Package', axis: 'disorder',
    desc: 'Comprehensive autoimmune screening covering rheumatological, thyroid, and systemic autoimmune conditions.',
    match: c => /autoimmune|ana|anti.*dsdna|anti.*smith|anti.*RNP|sjogren|scleroderma|myositis|vasculitis|complement|anti.*cardiolipin|anti.*ccp|rheumatoid.*factor|cryoglobulin|immune.*complex|coeliac|celiac|tTG|gliadin|endomysial|hla/i.test(c) },
  { slug: 'bleeding-clotting', name: 'Bleeding & Clotting Disorders Package', axis: 'disorder',
    desc: 'Complete coagulation assessment for bleeding disorders, thrombophilia, and anticoagulant monitoring.',
    match: c => /coagulation|pt|inr|aptt|ptt|fibrinogen|d.dimer|bleeding.*time|clotting.*time|platelet|vWF|von.*willebrand|factor|protein c|protein s|antithrombin|plasminogen|dilute.*russell|lupus.*anticoagulant|anti.*xa|warfarin|thrombin|thrombophilia|pfa|aggregometry/i.test(c) },
  { slug: 'metabolic-package', name: 'Metabolic Health Package', axis: 'disorder',
    desc: 'Metabolic syndrome screening covering diabetes risk, lipid profile, liver, and kidney function.',
    match: c => /diabetes|HbA1c|glucose|insulin|lipid|cholesterol|triglyceride|liver|kidney|uric acid|metabolic/i.test(c) },
  { slug: 'hormone-health', name: 'Hormonal Disorder Package', axis: 'disorder',
    desc: 'Comprehensive hormone panel covering reproductive, adrenal, pituitary, and metabolic hormones.',
    match: c => /hormone|cortisol|prolactin|testosterone|estradiol|progesterone|fsh|lh|amh|dhea|shbg|pth|aldosterone|renin|androstenedione|pregnenolone|growth|igf|leptin|adiponectin|17-oh|acth|neurosteroid|dexamethasone/i.test(c) },
  { slug: 'nutritional-deficiency', name: 'Nutritional Deficiency Package', axis: 'disorder',
    desc: 'Comprehensive nutritional assessment covering vitamins, minerals, and protein status markers.',
    match: c => /vitamin D|vitamin B12|folate|folic|iron|ferritin|calcium|magnesium|zinc|copper|selenium|iodine|total.*protein|albumin|prealbumin|transferrin|b1|b2|b3|b5|b6|biotin|vitamin a|retinol|vitamin e|tocopherol|vitamin k|coq10|carnitine|amino.*acid|organic.*acid/i.test(c) },

  // ── 4. AGE WISE ──
  { slug: 'newborn-screening', name: 'Newborn Screening Package', axis: 'age',
    desc: 'Essential health screening for newborns covering congenital disorders, thyroid, and metabolic conditions.',
    match: c => true, priceMultiplier: 0.55,
    filterTests: t => /CBC|bilirubin.total|TSH|glucose|G6PD|thyroid|blood.*group/i.test(t.name) && t.price <= 599 },
  { slug: 'pediatric-package', name: 'Pediatric Health Package (1-12 Years)', axis: 'age',
    desc: 'Child health screening covering growth markers, anemia, vitamin levels, and common childhood conditions.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|vitamin D|vitamin B12|TSH|urine.*routine|stool/i.test(t.name + t.category) && t.price <= 799 },
  { slug: 'adolescent-health', name: 'Adolescent Health Package (13-17 Years)', axis: 'age',
    desc: 'Health screening for teenagers covering hormonal changes, anemia, vitamin levels, and lifestyle risks.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|vitamin D|vitamin B12|TSH|lipid|glucose|urine.*routine/i.test(t.name + t.category) && t.price <= 799 },
  { slug: 'adult-wellness', name: 'Adult Wellness Package (18-40 Years)', axis: 'age',
    desc: 'Essential health screening for young adults covering baseline organ function and lifestyle risks.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|diabetes|thyroid|lipid|liver|kidney|vitamin D|vitamin B12|iron|uric.*acid|urine.*routine/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },
  { slug: 'midlife-health', name: 'Midlife Health Package (40-60 Years)', axis: 'age',
    desc: 'Comprehensive screening for adults 40-60 covering age-related risks including cardiac, diabetes, and cancer markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /cardiac|lipid|diabetes|HbA1c|thyroid|liver|kidney|vitamin D|vitamin B12|iron|cancer|psa|ca.*marker|uric.*acid|cortisol|testosterone|cbc|urine.*routine|stool.*occult/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'senior-citizen', name: 'Senior Citizen Health Package (60+)', axis: 'age',
    desc: 'Comprehensive health screening for adults 60+ covering all major age-related health risks.',
    match: c => true, priceMultiplier: 0.55,
    filterTests: t => /CBC|cardiac|diabetes|thyroid|liver|kidney|vitamin D|vitamin B12|iron|cancer|psa|ca.*marker|uric.*acid|cortisol|testosterone|urine.*routine|stool.*occult/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },

  // ── 5. GENDER WISE ──
  { slug: 'womens-health', name: "Women's Health Package", axis: 'gender',
    desc: 'Comprehensive women\'s health screening covering hormones, fertility, breast health, and gynecological markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Thyroid|Anemia|Vitamins|Hormones|Pregnancy|Cancer|CBC|lipid|diabetes|iron|calcium|vitamin D|prolactin|fsh|lh|estradiol|progesterone|amh|pap|ca 125|he4|rubella/i.test(t.category + t.subcategory + t.name) },
  { slug: 'mens-health', name: "Men's Health Package", axis: 'gender',
    desc: 'Comprehensive men\'s health screening covering prostate, cardiac, diabetes, and hormone health.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|Diabetes|Thyroid|Liver|Kidney|Prostate|Testosterone|CBC|lipid|psa|creatinine|uric.*acid|vitamin D|B12/i.test(t.category + t.subcategory + t.name) },
  { slug: 'transgender-health', name: 'Transgender Health Package', axis: 'gender',
    desc: 'Health screening for transgender individuals covering hormone levels, organ function, and preventive care.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|thyroid|lipid|glucose|liver|kidney|vitamin D|B12|iron|testosterone|estradiol|prolactin|fsh|lh|shbg|dhea|cortisol|calcium|uric.*acid|urine.*routine/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 6. LIFESTYLE WISE ──
  { slug: 'corporate-wellness', name: 'Corporate Wellness Package', axis: 'lifestyle',
    desc: 'Designed for working professionals covering stress markers, cardiac risk, diabetes, and lifestyle-related health issues.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|Diabetes|Thyroid|Liver|Kidney|Vitamins|Cortisol|Lipid|CBC|uric.*acid|iron|B12|vitamin D/i.test(t.category + t.subcategory) },
  { slug: 'smoker-package', name: 'Smoker\'s Health Assessment Package', axis: 'lifestyle',
    desc: 'Targeted health screening for smokers covering lung health, cardiac risk, and cancer markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|lipid|hs.crp|troponin|Lung|cancer|CYFRA|SCC|NSE|CBC|vitamin.*b12|vitamin.*c|urine.*routine|stool.*occult|creatinine|BUN|liver|GGT/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'alcohol-health', name: 'Alcohol Health Impact Package', axis: 'lifestyle',
    desc: 'Health screening for regular alcohol consumers covering liver damage, nutrition, and metabolic markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Liver|GGT|SGOT|SGPT|bilirubin|CBC|MCV|B12|folate|vitamin D|lipid|glucose|uric.*acid|creatinine|ammonia|electrolyte|magnesium|zinc/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'fitness-sports', name: 'Fitness & Sports Package', axis: 'lifestyle',
    desc: 'For athletes and fitness enthusiasts covering muscle health, iron status, hydration, and performance markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Iron|Testosterone|Creatinine|Kidney|Thyroid|HbA1c|CBC|Electrolyte|Vitamin D|Cortisol|magnesium|calcium|uric.*acid|total.*protein|albumin|creatine.*kinase|cpk|ldh/i.test(t.name + t.category + t.subcategory) },
  { slug: 'sedentary-lifestyle', name: 'Sedentary Lifestyle Health Package', axis: 'lifestyle',
    desc: 'For sedentary individuals covering metabolic syndrome, cardiac risk, diabetes, and vitamin deficiencies.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|lipid|diabetes|HbA1c|glucose|insulin|liver|kidney|vitamin D|vitamin B12|thyroid|CBC|uric.*acid|cortisol|iron/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'vegan-wellness', name: 'Vegan & Vegetarian Health Package', axis: 'lifestyle',
    desc: 'Targeted screening for plant-based diet followers covering B12, iron, vitamin D, calcium, and protein status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Vitamin B12|Folate|Iron|Ferritin|Vitamin D|Calcium|Total.*Protein|Albumin|CBC|Zinc|Iodine|Homocysteine|copper|magnesium|phosphorus/i.test(t.name + t.subcategory + t.category) },

  // ── 7. LIFE STAGE WISE ──
  { slug: 'premarital-package', name: 'Pre-Marital Health Checkup', axis: 'lifeStage',
    desc: 'Health screening for couples planning marriage covering genetic disorders, infectious diseases, and fertility markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|RPR|blood.*group|rh.*factor|thyroid|TSH|rubella|sickle|thalassemia|hemoglobin.*electro/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'preconception-package', name: 'Pre-Conception Health Package', axis: 'lifeStage',
    desc: 'Pre-pregnancy health screening for couples covering fertility markers, genetic screening, and nutritional status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /AMH|FSH|LH|prolactin|TSH|thyroid|vitamin D|B12|folate|iron|rubella|HIV|Hepatitis|VDRL|blood.*group|CBC|urine.*routine|hormone|estradiol|progesterone|testosterone|semen|sperm/i.test(t.name + t.category + t.subcategory) },
  { slug: 'pregnancy-package', name: 'Pregnancy Wellness Package', axis: 'lifeStage',
    desc: 'Comprehensive pregnancy monitoring covering prenatal screening, nutritional status, and maternal health.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Pregnancy|hCG|antenatal|TORCH|rubella|toxoplasma|CMV|triple.*marker|NIPT|glucose.*gestational|OGTT|iron|vitamin D|B12|folate|TSH|thyroid|CBC|urine.*routine|blood.*group|HIV|Hepatitis|VDRL/i.test(t.name + t.category + t.subcategory) },
  { slug: 'postpartum-package', name: 'Postpartum Health Package', axis: 'lifeStage',
    desc: 'Post-delivery health check for mothers covering recovery markers, hormonal balance, and nutritional status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|ferritin|thyroid|TSH|vitamin D|B12|folate|calcium|hormone|prolactin|cortisol|glucose|urine.*routine|lipid|total.*protein|albumin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'menopause-package', name: 'Menopause Health Package', axis: 'lifeStage',
    desc: 'Perimenopause and menopause health assessment covering hormonal changes, bone health, and cardiac risk.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /FSH|LH|estradiol|progesterone|TSH|thyroid|vitamin D|calcium|bone|lipid|cardiac|CBC|glucose|cortisol|iron|magnesium|homocysteine|hs.crp|PTH/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'andropause-package', name: 'Andropause (Male Menopause) Package', axis: 'lifeStage',
    desc: 'Age-related hormone decline assessment for men covering testosterone, prostate, and metabolic health.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Testosterone|prolactin|FSH|LH|SHBG|PSA|thyroid|TSH|lipid|cardiac|glucose|HbA1c|vitamin D|B12|creatinine|CBC|liver|uric.*acid|dhea|cortisol|estradiol/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },

  // ── 8. SYMPTOM WISE ──
  { slug: 'fever-panel', name: 'Fever Panel (Comprehensive)', axis: 'symptom',
    desc: 'Complete fever workup covering dengue, malaria, typhoid, chikungunya, leptospira, and COVID-19.',
    match: c => /fever|infection|dengue|malaria|typhoid|chikungunya|leptospira|scrub.*typhus|covid|CRP|procalcitonin|blood.*culture|ebv|widal|weil.*felix|brucella|zika|chikungunya/i.test(c) },
  { slug: 'fatigue-panel', name: 'Chronic Fatigue Assessment Package', axis: 'symptom',
    desc: 'Evaluation for persistent fatigue covering anemia, thyroid, diabetes, vitamin deficiencies, and hormonal causes.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|ferritin|thyroid|TSH|vitamin D|B12|folate|HbA1c|glucose|cortisol|creatinine|uric.*acid|electrolyte|total.*protein|albumin|liver|ck|cpk|calcium|magnesium|testosterone|prolactin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'hair-loss-package', name: 'Hair Loss Assessment Package', axis: 'symptom',
    desc: 'Hair loss diagnostic workup covering hormonal causes, nutritional deficiencies, and thyroid function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /TSH|thyroid|iron|ferritin|vitamin D|B12|folate|CBC|total.*protein|albumin|calcium|zinc|testosterone|dhea|prolactin|cortisol|copper|homocysteine|SHBG/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'joint-pain-package', name: 'Joint Pain & Arthritis Package', axis: 'symptom',
    desc: 'Joint pain evaluation covering inflammatory markers, arthritis-specific antibodies, and metabolic causes.',
    match: c => /arthritis|rheumatoid|uric.*acid|gout|hs.crp|anti-ccp|ana|anti.*dsdna|hla-b27|complement|haptoglobin|cryoglobulin|calcium|vitamin D|PTH/i.test(c) },
  { slug: 'weight-loss-package', name: 'Unexplained Weight Loss Package', axis: 'symptom',
    desc: 'Diagnostic workup for unintentional weight loss covering diabetes, thyroid, malabsorption, and infection markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /HbA1c|glucose|thyroid|TSH|CBC|iron|vitamin B12|folate|vitamin D|liver|creatinine|total.*protein|albumin|calcium|stool|elastase|celiac|tTG|HIV|antibody/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 9. OCCUPATION WISE ──
  { slug: 'pre-employment', name: 'Pre-Employment Health Checkup', axis: 'occupation',
    desc: 'Standard pre-employment medical screening covering organ function, infectious diseases, and fitness for work.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|chest.*x.ray|urine.*routine|vision|hearing|blood.*group|creatinine|BUN|bilirubin|SGOT|SGPT|lipid|glucose|total.*protein|albumin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'travel-visa', name: 'Travel & Visa Medical Package', axis: 'occupation',
    desc: 'Health screening required for international travel, visa applications, and immigration medicals.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|RPR|chest.*x.ray|urine.*routine|blood.*group|creatinine|BUN|bilirubin|SGOT|SGPT|glucose|total.*protein|albumin|rubella|measles|mumps|varicella|polio|yellow.*fever/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'sports-clearance', name: 'Sports Clearance Package', axis: 'occupation',
    desc: 'Pre-participation screening for athletes covering cardiac, musculoskeletal, and metabolic fitness.',
    match: c => true, priceMultiplier: 0.4,
    filterTests: t => /CBC|cardiac|lipid|troponin|CK-MB|CPK|creatine.*kinase|creatinine|BUN|glucose|electrolyte|calcium|magnesium|uric.*acid|total.*protein|albumin|iron|vitamin D|testosterone|urine.*routine|stool|blood.*group/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'hospital-admission', name: 'Hospital Admission Package', axis: 'occupation',
    desc: 'Pre-admission health screening required before elective surgery or hospital admission.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|PT|INR|APTT|PTT|bleeding.*time|clotting.*time|platelet|creatinine|BUN|bilirubin|SGOT|SGPT|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|blood.*group|Rh.*factor|glucose|electrolyte|urine.*routine|chest.*x.ray/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'govt-scheme', name: 'Government Scheme Health Checkup', axis: 'occupation',
    desc: 'Standard health screening package compliant with government health scheme requirements.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /CBC|lipid|glucose|HbA1c|creatinine|BUN|bilirubin|SGOT|SGPT|urine.*routine|blood.*group|chest.*x.ray|ecg|vitamin D|B12|TSH|total.*protein|albumin|uric.*acid|calcium|electrolyte|stool.*occult/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },

  // ── 10. MEDICATION MONITORING WISE ──
  { slug: 'warfarin-monitoring', name: 'Warfarin / Anticoagulation Monitoring Package', axis: 'medication',
    desc: 'Regular monitoring for patients on warfarin or other anticoagulants covering INR, PT, and bleeding risk.',
    match: c => /coagulation|PT|INR|APTT|PTT|fibrinogen|anti.*xa|platelet|warfarin|acenocoumarol|thrombin|bleeding.*time|clotting.*time|factor|d.dimer/i.test(c) },
  { slug: 'diabetes-med-monitoring', name: 'Diabetes Medication Monitoring Package', axis: 'medication',
    desc: 'Monitoring for diabetic patients on medication covering HbA1c, glucose, kidney function, and metabolic markers.',
    match: c => /diabetes|HbA1c|glucose|insulin|c-peptide|ketone|creatinine|BUN|microalbumin|lipid|uric.*acid/i.test(c) },
  { slug: 'thyroid-med-monitoring', name: 'Thyroid Medication Monitoring Package', axis: 'medication',
    desc: 'Regular thyroid function monitoring for patients on levothyroxine or anti-thyroid medications.',
    match: c => /thyroid|TSH|T3|T4|free.*t3|free.*t4/i.test(c) },
  { slug: 'antiepileptic-monitoring', name: 'Anti-Epileptic Drug Monitoring Package', axis: 'medication',
    desc: 'Therapeutic drug monitoring for patients on anti-epileptic medications covering drug levels and organ function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|liver|creatinine|BUN|electrolyte|calcium|magnesium|total.*protein|albumin|vitamin D|folate|uric.*acid/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },
  { slug: 'lithium-monitoring', name: 'Lithium Monitoring Package', axis: 'medication',
    desc: 'Regular monitoring for patients on lithium therapy covering renal function, electrolytes, and thyroid.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|creatinine|BUN|electrolyte|sodium|potassium|calcium|magnesium|thyroid|TSH|urine.*routine|urine.*osmolality|glucose|uric.*acid/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },

  // ── 11. FAMILY HISTORY / GENETIC WISE ──
  { slug: 'family-cardiac-risk', name: 'Family Cardiac Risk Package', axis: 'familyHistory',
    desc: 'Advanced cardiac risk assessment for individuals with family history of heart disease.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|lipid|cholesterol|hs.crp|troponin|homocysteine|apolipoprotein|lipoprotein|ck-mb|CBC|creatinine|BUN|glucose|HbA1c|uric.*acid|electrolyte|calcium|magnesium/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'family-cancer-risk', name: 'Family Cancer Predisposition Package', axis: 'familyHistory',
    desc: 'Early cancer screening for individuals with family history of cancer covering tumor markers and genetic testing.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cancer|tumor|CA 125|CA 19-9|CA 15-3|PSA|CEA|AFP|CYFRA|SCC|NSE|pap.*smear|occult.*blood|BRCA|thyroglobulin|calcitonin|HE4|stool.*occult|FIT|colon/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'family-diabetes-risk', name: 'Family Diabetes Heredity Package', axis: 'familyHistory',
    desc: 'Diabetes risk assessment for individuals with family history of diabetes covering glucose metabolism and related markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Diabetes|HbA1c|glucose|insulin|c-peptide|fructosamine|OGTT|lipid|creatinine|BUN|uric.*acid|thyroid|TSH|CBC|microalbumin|cortisol/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'genetic-health-screening', name: 'Genetic Health Risk Screening', axis: 'familyHistory',
    desc: 'Genetic screening for hereditary conditions including thalassemia, sickle cell, and thrombophilia markers.',
    match: c => /genetic|hereditary|thalassemia|sickle|hemoglobin.*electro|G6PD|factor.*v|prothrombin|MTHFR|HFE|hemochromatosis|HLA-B27|BRCA|cystic.*fibrosis|CFTR|inherited|familial|mutation|carrier/i.test(c) },

  // ── 12. SEASONAL WISE ──
  { slug: 'monsoon-package', name: 'Monsoon Illness Package', axis: 'seasonal',
    desc: 'Complete diagnostic panel for monsoon-related illnesses including dengue, malaria, typhoid, leptospira, and respiratory infections.',
    match: c => /dengue|malaria|typhoid|chikungunya|leptospira|scrub.*typhus|covid|CRP|procalcitonin|CBC|platelet|cold.*agglutinin|widal|weil.*felix|influenza|RSV|adenovirus|pneumonia|blood.*culture/i.test(c) },
  { slug: 'winter-package', name: 'Winter Wellness Package', axis: 'seasonal',
    desc: 'Seasonal health assessment for winter months covering respiratory infections, vitamin D, flu, and cold-related markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|CRP|vitamin D|vitamin C|zinc|thyroid|TSH|dengue|malaria|typhoid|covid|influenza|RSV|adenovirus|respiratory|pneumonia|procalcitonin|blood.*culture|urine.*routine|iron/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'summer-package', name: 'Summer Health Package', axis: 'seasonal',
    desc: 'Seasonal health assessment for summer months covering hydration, heat-related markers, and gastrointestinal health.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|electrolyte|sodium|potassium|chloride|creatinine|BUN|uric.*acid|urine.*routine|stool|typhoid|hepatitis A|hepatitis E|dehydration|osmolality|total.*protein|albumin|calcium|magnesium|glucose|lipid|liver/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },

  // ── 13. DIET WISE ──
  { slug: 'vegan-veg-package', name: 'Vegan & Vegetarian Nutrition Package', axis: 'diet',
    desc: 'Targeted screening for plant-based diet followers covering B12, iron, vitamin D, calcium, and protein status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Vitamin B12|Folate|Iron|Ferritin|Vitamin D|Calcium|Total.*Protein|Albumin|CBC|Zinc|Iodine|Homocysteine|copper|magnesium|phosphorus/i.test(t.name + t.subcategory + t.category) },
  { slug: 'high-protein-diet', name: 'High-Protein Diet Monitoring Package', axis: 'diet',
    desc: 'Health monitoring for individuals on high-protein diets covering kidney function, uric acid, and metabolic markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /creatinine|BUN|uric.*acid|total.*protein|albumin|calcium|electrolyte|sodium|potassium|magnesium|phosphorus|CBC|glucose|lipid|liver|SGOT|SGPT|GGT|urine.*routine|urine.*osmolality|vitamin D/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'keto-diet', name: 'Keto Diet Monitoring Package', axis: 'diet',
    desc: 'Regular monitoring for individuals on ketogenic diet covering ketones, lipid profile, electrolytes, and organ function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /ketone|beta.*hydroxybutyrate|acetoacetate|lipid|cholesterol|triglyceride|electrolyte|sodium|potassium|creatinine|BUN|uric.*acid|calcium|magnesium|CBC|glucose|HbA1c|liver|SGOT|SGPT|GGT|total.*protein|albumin|thyroid|TSH|vitamin D|B12|iron|ferritin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'malnutrition-package', name: 'Malnutrition Assessment Package', axis: 'diet',
    desc: 'Comprehensive nutritional deficiency screening covering vitamins, minerals, proteins, and essential nutrients.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Total.*Protein|Albumin|Prealbumin|Transferrin|CBC|iron|ferritin|vitamin D|vitamin B12|folate|calcium|magnesium|zinc|copper|iodine|phosphorus|vitamin A|retinol|vitamin E|tocopherol|vitamin K|biotin|b1|b2|b3|b5|b6|carnitine|amino.*acid|organic.*acid|homocysteine|glucose|creatinine|BUN/i.test(t.name + t.category + t.subcategory) && t.price <= 799 },

  // ── 14. POST-RECOVERY WISE ──
  { slug: 'post-covid', name: 'Post-COVID Recovery Package', axis: 'postRecovery',
    desc: 'Comprehensive health assessment after COVID-19 recovery covering lung function, cardiac markers, and immune status.',
    match: c => /CBC|CRP|hs.crp|D.dimer|ferritin|LDH|procalcitonin|IL-6|troponin|ck-mb|creatinine|BUN|SGOT|SGPT|bilirubin|total.*protein|albumin|glucose|HbA1c|vitamin D|B12|electrolyte|Covid|SARS|IgG|IgM|antibody|pulmonary|respiratory|oxygen|saturation|pulse|oximeter/i.test(c) },
  { slug: 'post-surgery', name: 'Post-Surgery Recovery Package', axis: 'postRecovery',
    desc: 'Post-operative health monitoring covering healing markers, infection screening, and nutritional recovery.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|CRP|procalcitonin|creatinine|BUN|glucose|electrolyte|sodium|potassium|calcium|magnesium|total.*protein|albumin|prealbumin|iron|vitamin D|B12|folate|liver|SGOT|SGPT|bilirubin|PT|INR|APTT|fibrinogen|D.dimer|uric.*acid|urine.*routine|wound|culture|blood.*culture/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'post-chemo', name: 'Post-Chemotherapy Monitoring Package', axis: 'postRecovery',
    desc: 'Regular health monitoring after chemotherapy covering blood counts, organ function, and nutritional status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|platelet|neutrophil|creatinine|BUN|SGOT|SGPT|bilirubin|GGT|alkaline.*phosphatase|total.*protein|albumin|glucose|electrolyte|calcium|magnesium|uric.*acid|LDH|vitamin D|B12|folate|iron|ferritin|urine.*routine|tumor|marker/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'post-heart-attack', name: 'Post-Heart Attack Recovery Package', axis: 'postRecovery',
    desc: 'Cardiac recovery monitoring after myocardial infarction covering heart function, inflammation, and risk markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Cardiac|lipid|hs.crp|troponin|ck-mb|NT-proBNP|BNP|creatinine|BUN|electrolyte|glucose|HbA1c|CBC|PT|INR|homocysteine|apolipoprotein|lipoprotein|uric.*acid|calcium|magnesium|total.*protein|albumin|thyroid|TSH|vitamin D/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'post-stroke', name: 'Post-Stroke Recovery Package', axis: 'postRecovery',
    desc: 'Stroke recovery monitoring covering neurological markers, vascular health, and rehabilitation progress.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|PT|INR|APTT|lipid|hs.crp|homocysteine|creatinine|BUN|electrolyte|glucose|HbA1c|uric.*acid|calcium|magnesium|total.*protein|albumin|thyroid|TSH|vitamin D|B12|folate|iron|ferritin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 15. TRAVEL WISE ──
  { slug: 'pre-travel', name: 'Pre-Travel Vaccination & Titers Package', axis: 'travel',
    desc: 'Pre-travel health assessment including vaccination titers, infectious disease screening, and fitness for travel.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|rubella|measles|mumps|varicella|polio|yellow.*fever|typhoid|dengue|malaria|COVID|antibody|IgG|IgM|creatinine|BUN|SGOT|SGPT|bilirubin|glucose|total.*protein|albumin|urine.*routine|stool|blood.*group/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'post-travel', name: 'Post-Travel Infectious Screen Package', axis: 'travel',
    desc: 'Health screening after international travel covering tropical diseases and infectious illness markers.',
    match: c => /dengue|malaria|typhoid|chikungunya|leptospira|scrub.*typhus|covid|influenza|ebv|zika|hepatitis A|hepatitis E|TB|tuberculosis|quantiFERON|blood.*culture|stool.*culture|CRP|CBC|procalcitonin|eosinophil|parasite/i.test(c) },
  { slug: 'visa-medical', name: 'Visa & Immigration Medical Package', axis: 'travel',
    desc: 'Health screening compliant with visa and immigration medical requirements of destination countries.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|RPR|chest.*x.ray|urine.*routine|blood.*group|creatinine|BUN|bilirubin|SGOT|SGPT|glucose|total.*protein|albumin|rubella|measles|mumps|varicella|polio|yellow.*fever|TB|tuberculosis|quantiFERON|mantoux/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 16. INSURANCE / CORPORATE WISE ──
  { slug: 'corporate-annual', name: 'Corporate Annual Health Checkup', axis: 'insurance',
    desc: 'Standard annual health screening for corporate employees covering all major organ systems and lifestyle diseases.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|lipid|glucose|HbA1c|creatinine|BUN|bilirubin|SGOT|SGPT|urine.*routine|chest.*x.ray|ecg|vitamin D|B12|TSH|uric.*acid|calcium|total.*protein|albumin|iron/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'insurance-medical', name: 'Insurance Medical Examination Package', axis: 'insurance',
    desc: 'Health screening required for life and health insurance policy approval covering baseline health assessment.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|lipid|glucose|HbA1c|creatinine|BUN|bilirubin|SGOT|SGPT|urine.*routine|ecg|TSH|uric.*acid|total.*protein|albumin|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|blood.*group|chest.*x.ray/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'govt-health-scheme', name: 'Government Health Scheme Package', axis: 'insurance',
    desc: 'Health screening compliant with Ayushman Bharat and other government health scheme requirements.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /CBC|lipid|glucose|HbA1c|creatinine|BUN|bilirubin|SGOT|SGPT|urine.*routine|blood.*group|ecg|vitamin D|B12|TSH|total.*protein|albumin|uric.*acid|calcium|electrolyte|chest.*x.ray|stool.*occult/i.test(t.name + t.category + t.subcategory) && t.price <= 599 },

  // ── 17. PREVENTIVE SCREENING WISE ──
  { slug: 'annual-master', name: 'Annual Master Health Checkup', axis: 'preventive',
    desc: 'Comprehensive annual preventive health screening covering all major organ systems and disease markers.',
    match: c => true, priceMultiplier: 0.4,
    filterTests: t => /CBC|cardiac|lipid|diabetes|HbA1c|glucose|thyroid|TSH|liver|kidney|creatinine|BUN|vitamin D|vitamin B12|uric.*acid|calcium|electrolyte|total.*protein|albumin|urine.*routine|stool.*occult|chest.*x.ray|ecg|iron|hs.crp|homocysteine|PSA|CA.*marker|AFP|CEA|pap.*smear|HPV|mammo/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'cancer-preventive', name: 'Preventive Cancer Screening Package', axis: 'preventive',
    desc: 'Early cancer detection package for asymptomatic individuals covering most common cancer markers.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /Cancer|tumor|CA 125|CA 19-9|CA 15-3|PSA|CEA|AFP|CYFRA|SCC|NSE|pap.*smear|HPV|occult.*blood|FIT|colorectal|BRCA|thyroglobulin|calcitonin|HE4|mammo|gyn/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'wellness-panel', name: 'Complete Wellness Panel', axis: 'preventive',
    desc: 'Holistic wellness assessment covering physical health markers, nutritional status, and lifestyle risk factors.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /CBC|lipid|glucose|HbA1c|thyroid|TSH|creatinine|BUN|uric.*acid|vitamin D|vitamin B12|folate|iron|ferritin|calcium|magnesium|total.*protein|albumin|hs.crp|homocysteine|cortisol|testosterone|estradiol|prolactin|urine.*routine|stool.*occult|ecg|chest.*x.ray/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 18. BUDGET / PRICE TIER WISE ──
  { slug: 'silver-package', name: 'Silver Health Checkup (₹999)', axis: 'budget',
    desc: 'Essential health screening at an affordable price covering CBC, blood sugar, thyroid, and basic organ function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|glucose|thyroid|TSH|creatinine|BUN|bilirubin|SGOT|SGPT|uric.*acid|urine.*routine|lipid|total.*cholesterol/i.test(t.name + t.category + t.subcategory) && t.price <= 399 },
  { slug: 'gold-package', name: 'Gold Health Checkup (₹2,499)', axis: 'budget',
    desc: 'Mid-range comprehensive screening including advanced cardiac markers, vitamins, and extended organ function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|lipid|glucose|HbA1c|thyroid|TSH|creatinine|BUN|bilirubin|SGOT|SGPT|uric.*acid|vitamin D|vitamin B12|iron|ferritin|calcium|magnesium|total.*protein|albumin|urine.*routine|stool.*occult|ecg|hs.crp|homocysteine/i.test(t.name + t.category + t.subcategory) && t.price <= 699 },
  { slug: 'platinum-package', name: 'Platinum Health Checkup (₹3,999)', axis: 'budget',
    desc: 'Premium comprehensive checkup with advanced diagnostics, tumor markers, hormones, and specialty tests.',
    match: c => true, priceMultiplier: 0.4,
    filterTests: t => /CBC|lipid|glucose|HbA1c|thyroid|TSH|creatinine|BUN|bilirubin|SGOT|SGPT|GGT|alkaline.*phosphatase|uric.*acid|vitamin D|vitamin B12|folate|iron|ferritin|calcium|magnesium|electrolyte|total.*protein|albumin|hs.crp|homocysteine|cortisol|testosterone|prolactin|PSA|CA.*marker|AFP|CEA|urine.*routine|stool.*occult|ecg|chest.*x.ray|pap.*smear/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },

  // ── 19. RISK PROFILE WISE ──
  { slug: 'high-risk', name: 'High Risk Health Assessment', axis: 'risk',
    desc: 'Comprehensive screening for individuals at high risk due to family history, lifestyle, or pre-existing conditions.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|cardiac|lipid|hs.crp|troponin|diabetes|HbA1c|glucose|insulin|thyroid|TSH|liver|SGOT|SGPT|GGT|bilirubin|kidney|creatinine|BUN|cancer|PSA|CA.*marker|AFP|CEA|vitamin D|B12|iron|homocysteine|uric.*acid|electrolyte|urine.*routine|stool.*occult|ecg|cortisol|testosterone/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'medium-risk', name: 'Moderate Risk Health Checkup', axis: 'risk',
    desc: 'Standard preventive screening for individuals with moderate risk profile covering major organ systems.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|lipid|glucose|HbA1c|thyroid|TSH|creatinine|BUN|bilirubin|SGOT|SGPT|uric.*acid|vitamin D|vitamin B12|calcium|total.*protein|albumin|urine.*routine|ecg|hs.crp|iron/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'low-risk', name: 'Low Risk / Routine Checkup', axis: 'risk',
    desc: 'Basic health checkup for low-risk asymptomatic individuals covering essential health markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|glucose|thyroid|TSH|creatinine|BUN|bilirubin|SGOT|SGPT|uric.*acid|urine.*routine|lipid|total.*cholesterol/i.test(t.name + t.category + t.subcategory) && t.price <= 499 },

  // ── 20. DURATION / URGENCY WISE ──
  { slug: 'instant-package', name: 'Instant Results Package (30 Min)', axis: 'duration',
    desc: 'Rapid diagnostic package with immediate results for urgent health concerns.',
    match: c => true, priceMultiplier: 0.6,
    filterTests: t => /glucose|blood.*sugar|hemoglobin|CBC|urine.*routine|pregnancy.*test|hCG|dengue.*NS1|malaria.*rapid|typhoid.*rapid|CRP|influenza|COVID.*rapid|blood.*group|HbA1c|ketone/i.test(t.name + t.category + t.subcategory) && (t.report_time === 'Immediate' || t.report_time === '6 hrs') },
  { slug: 'same-day-package', name: 'Same-Day Health Checkup', axis: 'duration',
    desc: 'Health checkup with results available within 24 hours covering essential diagnostic markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|glucose|HbA1c|creatinine|BUN|bilirubin|SGOT|SGPT|uric.*acid|thyroid|TSH|urine.*routine|lipid|calcium|electrolyte|total.*protein|albumin|iron|vitamin D|B12|hs.crp/i.test(t.name + t.category + t.subcategory) && (t.report_time === '6 hrs' || t.report_time === '12 hrs' || t.report_time === '24 hrs') },
  { slug: 'comprehensive-week', name: 'Comprehensive Week-Long Assessment', axis: 'duration',
    desc: 'Extended diagnostic assessment with results over 5-7 days covering advanced and specialty tests.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /CBC|cardiac|lipid|diabetes|HbA1c|glucose|thyroid|TSH|liver|kidney|creatinine|BUN|vitamin D|vitamin B12|folate|iron|ferritin|uric.*acid|calcium|electrolyte|total.*protein|albumin|hs.crp|homocysteine|cortisol|testosterone|PSA|CA.*marker|AFP|CEA|cancer|tumor|allergy|autoimmune|ANA|coagulation|PT|INR|APTT|urine.*routine|stool.*occult|ecg/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },

  // ── 21. MENTAL HEALTH WISE ──
  { slug: 'stress-panel', name: 'Stress & Adrenal Health Package', axis: 'mentalHealth',
    desc: 'Comprehensive stress assessment covering cortisol rhythm, adrenal function, thyroid, and metabolic impact.',
    match: c => /cortisol|DHEA|adrenal|ACTH|dexamethasone|synacthen|thyroid|TSH|T3|T4|prolactin|testosterone|estradiol|progesterone|insulin|glucose|HbA1c|lipid|creatinine|CBC|vitamin D|B12|folate|magnesium|zinc|homocysteine|hs.crp|serotonin|dopamine|neurotransmitter/i.test(c) },
  { slug: 'sleep-package', name: 'Sleep Health & Circadian Package', axis: 'mentalHealth',
    desc: 'Sleep health assessment covering circadian rhythm markers, cortisol profile, and common sleep disorder indicators.',
    match: c => /cortisol|melatonin|thyroid|TSH|iron|ferritin|vitamin D|B12|folate|magnesium|electrolyte|CBC|glucose|HbA1c|lipid|creatinine|BUN|uric.*acid|total.*protein|albumin|calcium|homocysteine|hs.crp|prolactin|testosterone|estradiol|progesterone|sleep|circadian/i.test(c) },
  { slug: 'depression-mood', name: 'Mood & Depression Markers Package', axis: 'mentalHealth',
    desc: 'Mood disorder assessment covering thyroid function, vitamin deficiencies, hormone balance, and inflammation markers.',
    match: c => /thyroid|TSH|T3|T4|vitamin D|B12|folate|iron|ferritin|CBC|cortisol|testosterone|estradiol|progesterone|prolactin|homocysteine|hs.crp|magnesium|zinc|creatinine|glucose|lipid|electrolyte|calcium|total.*protein|albumin|uric.*acid/i.test(c) },
  { slug: 'mental-wellness', name: 'Complete Mental Wellness Checkup', axis: 'mentalHealth',
    desc: 'Comprehensive mental health assessment covering all biological markers that influence mood, cognition, and mental wellbeing.',
    match: c => true, priceMultiplier: 0.45,
    filterTests: t => /Thyroid|TSH|vitamin D|B12|folate|iron|ferritin|CBC|cortisol|testosterone|estradiol|progesterone|prolactin|DHEA|homocysteine|hs.crp|magnesium|zinc|calcium|electrolyte|creatinine|glucose|HbA1c|lipid|uric.*acid|total.*protein|albumin|neurotransmitter|serotonin|dopamine|melatonin|pregnenolone|androstenedione|SHBG/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 22. FITNESS & SPORTS WISE ──
  { slug: 'pre-marathon', name: 'Pre-Marathon Health Screening', axis: 'fitness',
    desc: 'Pre-race health assessment covering cardiac fitness, hydration, nutrition, and performance readiness.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|ferritin|creatinine|BUN|glucose|HbA1c|electrolyte|sodium|potassium|calcium|magnesium|vitamin D|B12|folate|lipid|total.*protein|albumin|hs.crp|uric.*acid|CPK|creatine.*kinase|CK-MB|troponin|thyroid|TSH|testosterone|cortisol|iron|zinc|homocysteine|LDH/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'gym-bodybuilding', name: 'Gym & Bodybuilding Package', axis: 'fitness',
    desc: 'Health monitoring for strength athletes covering testosterone, kidney function, muscle enzymes, and nutritional status.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /Testosterone|creatinine|BUN|uric.*acid|CBC|iron|ferritin|vitamin D|B12|calcium|magnesium|electrolyte|sodium|potassium|lipid|glucose|HbA1c|total.*protein|albumin|CPK|creatine.*kinase|LDH|SGOT|SGPT|GGT|thyroid|TSH|cortisol|prolactin|SHBG|dhea|estradiol|homocysteine/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'endurance-athlete', name: 'Endurance Athlete Package', axis: 'fitness',
    desc: 'Health screening for endurance athletes covering hydration, iron metabolism, energy metabolism, and cardiac health.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|iron|ferritin|transferrin|vitamin B12|folate|vitamin D|calcium|magnesium|electrolyte|sodium|potassium|creatinine|BUN|glucose|HbA1c|lipid|thyroid|TSH|cortisol|testosterone|total.*protein|albumin|uric.*acid|CPK|LDH|hs.crp|homocysteine|iron|ferritin/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 23. SLEEP HEALTH WISE ──
  { slug: 'sleep-apnea', name: 'Sleep Apnea Risk Assessment', axis: 'sleep',
    desc: 'Sleep apnea screening covering associated health markers including cardiac risk, metabolic syndrome, and thyroid function.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|thyroid|TSH|glucose|HbA1c|lipid|creatinine|BUN|uric.*acid|electrolyte|calcium|magnesium|total.*protein|albumin|iron|vitamin D|B12|hs.crp|cortisol|testosterone|estradiol|prolactin|homocysteine|ecg|chest.*x.ray/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'circadian-rhythm', name: 'Circadian Rhythm & Hormone Package', axis: 'sleep',
    desc: 'Circadian rhythm assessment covering cortisol pattern, melatonin, and associated hormone markers.',
    match: c => /cortisol|melatonin|DHEA|testosterone|estradiol|progesterone|prolactin|TSH|thyroid|pregnenolone|androstenedione|growth.*hormone|IGF|glucose|insulin|HbA1c|vitamin D|B12|iron|calcium|magnesium|electrolyte|creatinine|BUN|CBC|lipid|total.*protein|albumin/i.test(c) },

  // ── 24. ENVIRONMENTAL / TOXIN WISE ──
  { slug: 'heavy-metal', name: 'Heavy Metal Toxicity Package', axis: 'environmental',
    desc: 'Screening for toxic heavy metal exposure covering lead, mercury, arsenic, cadmium, and related health markers.',
    match: c => /heavy metal|lead|mercury|arsenic|cadmium|aluminum|copper|zinc|selenium|toxicolo|chel.*at.*ion|environmental|occupation.*exposure|chromium|nickel|manganese|iron.*overload|hemochromatosis|ferritin|transferrin.*saturation|HFE/i.test(c) },
  { slug: 'air-pollution', name: 'Air Pollution Impact Package', axis: 'environmental',
    desc: 'Health screening for individuals exposed to air pollution covering respiratory, cardiac, and inflammatory markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|CRP|hs.crp|d.dimer|fibrinogen|homocysteine|lipid|glucose|HbA1c|creatinine|BUN|uric.*acid|electrolyte|calcium|magnesium|total.*protein|albumin|vitamin D|B12|folate|iron|ferritin|thyroid|TSH|cortisol|IgE|eosinophil|pulmonary|respiratory|chest.*x.ray|ecg|blood.*gas|carboxyhemoglobin|carbon.*monoxide/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },

  // ── 25. VACCINATION / IMMUNITY WISE ──
  { slug: 'antibody-titers', name: 'Vaccination Antibody Titers Package', axis: 'vaccination',
    desc: 'Immunity assessment measuring antibody levels for vaccine-preventable diseases.',
    match: c => /rubella|measles|mumps|varicella|Hepatitis B|HBsAb|anti.*HBs|polio|tetanus|diphtheria|pertussis|COVID.*antibody|IgG|IgM|immunity|vaccination|titer|antibody.*titer|vaccine|booster/i.test(c) },
  { slug: 'immune-status', name: 'Complete Immune Status Package', axis: 'vaccination',
    desc: 'Comprehensive immune system assessment covering immunoglobulin levels, antibody titers, and immune cell markers.',
    match: c => /immunoglobulin|IgG|IgM|IgA|IgE|CBC|lymphocyte|neutrophil|CD4|CD8|T.cell|B.cell|NK.cell|complement|C3|C4|HIV|antibody.*titer|vaccination|rubella|measles|mumps|varicella|HBsAb|COVID.*antibody|total.*protein|albumin|globulin|immunodeficiency|AIDS|HIV|viral.*load|PCR|genexpert/i.test(c) },
  { slug: 'allergy-immunity', name: 'Allergy & Immunity Panel', axis: 'vaccination',
    desc: 'Combined allergy and immunity assessment covering IgE levels, allergen panels, and immune cell function.',
    match: c => /allergy|IgE|eosinophil|mast.*cell|tryptase|histamine|immunoglobulin|CBC|lymphocyte|neutrophil|complement|C3|C4|total.*protein|albumin|globulin|food.*panel|inhalant.*panel|specific.*ige|RAST|contact.*allergen|patch.*test/i.test(c) },

  // ── 26. PRE-SURGICAL WISE ──
  { slug: 'pre-operative', name: 'Pre-Operative Health Package', axis: 'preSurgical',
    desc: 'Pre-surgery assessment covering clotting status, blood counts, organ function, and anesthesia clearance markers.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|PT|INR|APTT|PTT|bleeding.*time|clotting.*time|platelet|creatinine|BUN|bilirubin|SGOT|SGPT|glucose|electrolyte|sodium|potassium|calcium|total.*protein|albumin|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|blood.*group|Rh.*factor|urine.*routine|chest.*x.ray|ecg|troponin|CK-MB|echocardio/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'anesthesia-clearance', name: 'Anesthesia Clearance Package', axis: 'preSurgical',
    desc: 'Anesthesia fitness assessment covering cardiac evaluation, lung function, and metabolic stability.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|PT|INR|APTT|creatinine|BUN|bilirubin|SGOT|SGPT|glucose|electrolyte|calcium|total.*protein|albumin|ecg|chest.*x.ray|troponin|CK-MB|blood.*gas|pulmonary|spirometry|oxygen|saturation|LVEF|echocardio/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },

  // ── 27. ETHNICITY / REGION WISE ──
  { slug: 'south-asian', name: 'South Asian Health Risk Package', axis: 'ethnicity',
    desc: 'Targeted screening for South Asian populations who have higher risk of diabetes, heart disease, and metabolic syndrome.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /CBC|diabetes|HbA1c|glucose|insulin|cardiac|lipid|hs.crp|homocysteine|lipoprotein|apolipoprotein|creatinine|BUN|uric.*acid|thyroid|TSH|vitamin D|B12|iron|calcium|total.*protein|albumin|urine.*routine|ecg|stool.*occult|HbA1c|liver|SGOT|SGPT|bilirubin|GGT|ALP/i.test(t.name + t.category + t.subcategory) && t.price <= 999 },
  { slug: 'sickle-thalassemia', name: 'Sickle Cell & Thalassemia Screening Package', axis: 'ethnicity',
    desc: 'Genetic blood disorder screening for individuals from high-prevalence communities covering hemoglobin variants and anemia markers.',
    match: c => /sickle|thalassemia|hemoglobin.*electro|HbA2|HbF|HbS|HbC|HbE|HPLC|CBC|MCV|MCH|MCHC|RDW|iron|ferritin|RBC.*count|reticulocyte|osmotic.*fragility|G6PD|hereditary|genetic.*blood/i.test(c) },
  { slug: 'regional-endemic', name: 'Regional & Endemic Disease Package', axis: 'ethnicity',
    desc: 'Health screening tailored to region-specific endemic diseases and prevalent health conditions.',
    match: c => /dengue|malaria|typhoid|chikungunya|leptospira|scrub.*typhus|TB|tuberculosis|hepatitis|jejunum|entamoeba|giardia|leishmania|filariasis|schistosoma|brucella|plague|yellow.*fever|japanese.*encephalitis|zika|chikungunya|noma|river.*blindness|elephantiasis|leprosy|endemic|tropical|regional|local/i.test(c) },

  // ── 28. FERTILITY / REPRODUCTIVE WISE ──
  { slug: 'preconception-couples', name: 'Pre-Conception Couples Package', axis: 'fertility',
    desc: 'Pre-pregnancy health screening for both partners covering fertility markers, genetic screening, and infectious diseases.',
    match: c => true, priceMultiplier: 0.5,
    filterTests: t => /AMH|FSH|LH|prolactin|TSH|thyroid|vitamin D|B12|folate|iron|rubella|HIV|Hepatitis B|HBsAg|Hepatitis C|VDRL|blood.*group|Rh.*factor|CBC|urine.*routine|hormone|estradiol|progesterone|testosterone|semen|sperm|sperm.*count|sperm.*motility|sperm.*morphology|genetic|sickle|thalassemia|CFTR|karyotype|fragile.*X|TORCH|toxoplasma|CMV|herpes|HSV|chlamydia|gonorrhea|mycoplasma|ureaplasma/i.test(t.name + t.category + t.subcategory) && t.price <= 1499 },
  { slug: 'male-fertility', name: 'Male Fertility Assessment Package', axis: 'fertility',
    desc: 'Comprehensive male fertility evaluation covering semen analysis, hormone profile, and genetic screening.',
    match: c => /semen|sperm|sperm.*count|sperm.*motility|sperm.*morphology|sperm.*DNA|prostate|PSA|testosterone|FSH|LH|prolactin|SHBG|estradiol|cortisol|karyotype|fragile.*X|CFTR|Y.*chromosome|microdeletion|genetic|infertility|varicocele|creatinine|BUN|TSH|thyroid|vitamin D|B12|zinc|selenium|copper|CBC|urine.*routine|STD|HIV|Hepatitis|VDRL|chlamydia|gonorrhea/i.test(c) },
  { slug: 'female-fertility', name: 'Female Fertility Assessment Package', axis: 'fertility',
    desc: 'Comprehensive female fertility evaluation covering ovarian reserve, hormone balance, and reproductive health.',
    match: c => /AMH|FSH|LH|prolactin|estradiol|progesterone|testosterone|DHEA|SHBG|androstenedione|17-oh|thyroid|TSH|vitamin D|B12|folate|iron|ferritin|calcium|zinc|selenium|copper|rubella|toxoplasma|CMV|TORCH|HIV|Hepatitis|VDRL|HSV|HPV|pap.*smear|chlamydia|gonorrhea|CBC|urine.*routine|glucose|HbA1c|lipid|creatinine|BUN|genetic|sickle|thalassemia|CFTR|karyotype|fragile.*X/i.test(c) },
];

export function generatePackages(tests) {
  return PACKAGE_DEFS.map(def => {
    let matched;
    if (def.filterTests) {
      matched = tests.filter(def.filterTests);
    } else {
      matched = tests.filter(t => def.match(t.name + ' ' + t.category + ' ' + t.subcategory));
    }
    const totalMrp = matched.reduce((s, t) => s + (t.mrp || Math.round(t.price * 2.2)), 0);
    const multiplier = def.priceMultiplier || 0.45;
    const bundlePrice = Math.round(totalMrp * multiplier);
    const savings = totalMrp - bundlePrice;
    return {
      ...def,
      match: undefined,
      filterTests: undefined,
      priceMultiplier: undefined,
      testIds: matched.map(t => t.id),
      testNames: matched.map(t => t.name),
      testCount: matched.length,
      totalMrp,
      bundlePrice,
      savings,
      discountPct: Math.round((1 - multiplier) * 100),
      meta: AXIS_META[def.axis] || {},
    };
  });
}

export function getPackageBySlug(slug, tests) {
  return generatePackages(tests).find(p => p.slug === slug) || null;
}

export function getPackagesByAxis(tests) {
  const all = generatePackages(tests);
  const grouped = {};
  all.forEach(p => {
    if (!grouped[p.axis]) grouped[p.axis] = [];
    grouped[p.axis].push(p);
  });
  return grouped;
}
